src/Entity/AdminImage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminImageRepository")
 */
class AdminImage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $car_id;

    /**
     * @ORM\Column(length=150,nullable=true)
     */

    public $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCarId(): ?int
    {
        return $this->car_id;
    }

    public function setCarId(?int $car_id): self

    {
    $this->car_id = $car_id;

    return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
     $this->image = $image;

    return $this;
    }
}

src/Form/AdminImageType.php
<?php

namespace App\Form;

use App\Entity\AdminImage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdminImageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('car_id')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AdminImage::class,
            'csrf_protection'=>false,
        ]);
    }
}

src/Controller/AdminImageController.php
<?php

namespace App\Controller;

use App\Entity\AdminImage;
use App\Form\AdminImageType;
use App\Repository\AdminImageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DomCrawler\Image;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/image")
 */
class AdminImageController extends AbstractController
{
    /**
     * @Route("/", name="admin_image_index", methods="GET")
     */
    public function index(AdminImageRepository $adminImageRepository): Response
    {
        return $this->render('admin_image/index.html.twig', ['admin_images' => $adminImageRepository->findAll()]);
    }

    /**
     * @Route("/new/{pid}", name="admin_image_new", methods="GET|POST")
     */
    public function new(Request $request,$pid,AdminImageRepository $imageRepository): Response
    {
        $imageList = $imageRepository->findBy(['car_id' => $pid]);
        $adminImage = new AdminImage();
        $form = $this->createForm(AdminImageType::class, $adminImage);
        $form->handleRequest($request);
        if($request->files->get('imagename'))
        //if ($form->isSubmitted()
            {

            $file = $request->files->get('imagename');
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $adminImage->setImage($fileName);
            $adminImage->setCarId($pid);



            $em = $this->getDoctrine()->getManager();
            $em->persist($adminImage);
            $em->flush();

            return $this->redirectToRoute('admin_image_index',array('pid' => $pid));
        }

        return $this->render('admin_image/new.html.twig', [
            'admin_image' => $adminImage,
            'imageList' => $imageList,
            'pid' => $pid,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_image_show", methods="GET")
     */
    public function show(AdminImage $adminImage): Response
    {
        return $this->render('admin_image/show.html.twig', ['admin_image' => $adminImage]);
    }

    /**
     * @Route("/{id}/edit", name="admin_image_edit", methods="GET|POST")
     */
    public function edit(Request $request, AdminImage $adminImage): Response
    {
        $form = $this->createForm(AdminImageType::class, $adminImage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_image_index', ['id' => $adminImage->getId()]);
        }

        return $this->render('admin_image/edit.html.twig', [
            'admin_image' => $adminImage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_image_delete", methods="GET")
     */
    public function delete(Request $request, AdminImage $adminImage): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adminImage->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($adminImage);
            $em->flush();
        }

        return $this->redirectToRoute('admin_image_index');
    }
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/{id}/{pid}", name="admin_image_del", methods="GET")
     */
    public function del(Request $request, AdminImage $adminImage,$pid): Response
    {{
            $em = $this->getDoctrine()->getManager();
            $em->remove($adminImage);
            $em->flush();
        }

        return $this->redirectToRoute('admin_image_new',array('pid' => $pid));
    }




}

templates/admin_image/_delete_form.html.twig
<form method="post" action="{{ path('admin_image_delete', {'id': admin_image.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin_image.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_image/_form.html.twig
<form action="{{ path('admin_image_new',{'pid':pid}) }}" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input name="admin_car.id" type = "hidden" value="{{ pid }}" type="number" readonly>
    <input type="file" name="imagename" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>

templates/admin_image/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AdminImage{% endblock %}

{% block body %}
    <h1>Edit AdminImage</h1>

    {{ include('admin_image/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('admin_image_index') }}">back to list</a>

    {{ include('admin_image/_delete_form.html.twig') }}
{% endblock %}

templates/admin_image/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AdminImage index{% endblock %}

{% block body %}
    <h1>AdminImage index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Car_id</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for admin_image in admin_images %}
            <tr>
                <td>{{ admin_image.id }}</td>
                <td>{{ admin_image.carId }}</td>
                <td>{{ admin_image.image }}</td>
                <td>
                    <a href="{{ path('admin_image_show', {'id': admin_image.id}) }}">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/admin_image/new.html.twig
<h1>Create new AdminImage</h1>

    {{ include('admin_image/_form.html.twig') }}


{%  for image in imageList %}

    <img src="/uploads/{{ image.image }}" height="400" width="400">

    <a href="{{ path('admin_image_del',{'id':image.id,'pid':image.car_id}) }}" onclick="return confirm('Silinsin mi ?')" >Sil</a>


{% endfor %}

templates/admin_image/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AdminImage{% endblock %}

{% block body %}
    <h1>AdminImage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ admin_image.id }}</td>
            </tr>
            <tr>
                <th>Car_id</th>
                <td>{{ admin_image.carId }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ admin_image.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_image_index') }}">back to list</a>



    {{ include('admin_image/_delete_form.html.twig') }}
{% endblock %}