src/Entity/AdminCars.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminCarsRepository")
 */
class AdminCars
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    public $title;

    /**
     * @ORM\Column(type="string", length=150)
     */
    public $keywords;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    public $description;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    public $type;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $publisher_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $year;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $amount;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    public $price;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    public $saleprice;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    public $detail;

    /**
     * @ORM\Column(length=150,nullable=true)
     */
    public $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $writer_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $category_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $user_id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    public $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    #public function setTitle(?string $title): self
    #{
    #$this->title = $title;

    #return $this;
    #}

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    #public function setKeywords(string $keywords): self
    # {
    # $this->keywords = $keywords;

    #return $this;
    # }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    # public function setDescription(?string $description): self
    #{
    #  $this->description = $description;

    #   return $this;
    # }

    public function getType(): ?string
    {
        return $this->type;
    }

    # public function setType(?string $type): self
    # {
    # $this->type = $type;

    #    return $this;
    #}

    public function getPublisherId(): ?int
    {
        return $this->publisher_id;
    }

    # public function setPublisherId(?int $publisher_id): self
    #{
    #   $this->publisher_id = $publisher_id;

    #  return $this;
    #}

    public function getYear(): ?int
    {
        return $this->year;
    }

    # public function setYear(?int $year): self
    # {
    #  $this->year = $year;

    #  return $this;
    #}

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    #public function setAmount(?int $amount): self
    # {
    # $this->amount = $amount;

    # return $this;
    #}

    public function getPrice(): ?float
    {
        return $this->price;
    }

    #public function setPrice(?float $price): self
    #{
    # $this->price = $price;

    #return $this;
    #}

    public function getSaleprice(): ?float
    {
        return $this->saleprice;
    }

    #public function setSaleprice(?float $saleprice): self
    #{
    #$this->saleprice = $saleprice;

    #return $this;
    #}

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    #public function setDetail(?string $detail): self
    # {
    # $this->detail = $detail;

    #return $this;
    #}

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
    $this->image = $image;

    return $this;
     }

    public function getWriterId(): ?int
    {
        return $this->writer_id;
    }

    #public function setWriterId(?int $writer_id): self
    #{
    # $this->writer_id = $writer_id;

    # return $this;
    #}

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    # public function setCategoryId(?int $category_id): self
    #{
    # $this->category_id = $category_id;

    #return $this;
    # }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    #public function setUserId(?int $user_id): self
    #{
    # $this->user_id = $user_id;

    #return $this;
    #}

    public function getStatus(): ?string
    {
        return $this->status;
    }

    #public function setStatus(?string $status): self
    #{
    #$this->status = $status;

    #return $this;
    #}
}

src/Form/AdminCarsType.php
<?php

namespace App\Form;

use App\Entity\AdminCars;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdminCarsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('keywords')
            ->add('description')
            ->add('type')
            ->add('publisher_id')
            ->add('year')
            ->add('amount')
            ->add('price')
            ->add('saleprice')
            ->add('detail')
            ->add('image')
            ->add('writer_id')
            ->add('category_id')
            ->add('user_id')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AdminCars::class,
            'csrf_protection'=>false,
        ]);
    }
}

src/Controller/AdminCarsController.php
<?php

namespace App\Controller;

use App\Entity\AdminCars;
use App\Form\AdminCarsType;
use App\Repository\AdminCarsRepository;
use App\Repository\AdminCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/cars")
 */
class AdminCarsController extends AbstractController
{
    /**
     * @Route("/", name="admin_cars_index", methods="GET")
     */
    public function index(AdminCarsRepository $adminCarsRepository): Response
    {
        return $this->render('admin_cars/index.html.twig', ['admin_cars' => $adminCarsRepository->findAll()]);
    }

    /**
     * @Route("/new", name="admin_cars_new", methods="GET|POST")
     */
    public function new(Request $request,AdminCategoryRepository $categoryRepository): Response
    {   $catlist = $categoryRepository->findAll();
        $catname = $categoryRepository->findBy(['id' => 0]);
        $adminCar = new AdminCars();
        $form = $this->createForm(AdminCarsType::class, $adminCar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($adminCar);
            $em->flush();

            return $this->redirectToRoute('admin_cars_index');
        }

        return $this->render('admin_cars/new.html.twig', [
            'admin_car' => $adminCar,
            'catlist' => $catlist,
            'catname' => $catname,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_cars_show", methods="GET")
     */
    public function show(AdminCars $adminCar): Response
    {
        return $this->render('admin_cars/show.html.twig', ['admin_car' => $adminCar]);
    }

    /**
     * @Route("/{id}/edit", name="admin_cars_edit", methods="GET|POST")
     */
    public function edit(Request $request, $id,AdminCars $adminCar,AdminCategoryRepository $categoryRepository): Response
    {
        $productid = $adminCar->getUserId();

        $catlist = $categoryRepository->findAll();
        $catname = $categoryRepository->findBy(['id'=> $adminCar->getCategoryId()]);
        $form = $this->createForm(AdminCarsType::class, $adminCar);
        $form->handleRequest($request);
        $em = $this->getDoctrine()->getManager();
        if ($form->isSubmitted()) {
            $this->getDoctrine()->getManager()->flush();
            $pro = $adminCar->getId();
            $sql = 'UPDATE admin_cars set user_id = :productid WHERE id=:pro';
            $statement = $em->getConnection()->prepare($sql);
            $statement->bindParam(':productid',$productid);
            $statement->bindParam(':pro',$pro);
            $statement->execute();
            $this->addFlash("Success","Güncelleme Basarılı Bir Sekilde Tamamlandı.");
            return $this->redirectToRoute('admin_cars_index', ['id' => $adminCar->getId()]);

        }

        return $this->render('admin_cars/edit.html.twig', [
            'admin_car' => $adminCar,
            'catlist' => $catlist,
            'catname' => $catname,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_cars_delete", methods="DELETE")
     */
    public function delete(Request $request, AdminCars $adminCar): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adminCar->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($adminCar);
            $em->flush();
        }

        return $this->redirectToRoute('admin_cars_index');
    }
    /**
     * @Route("/{id}/iedit", name="admin_cars_iedit", methods="GET|POST")
     */
    public function iedit(Request $request,$id, AdminCars $adminCar): Response
    {
        $form = $this->createForm(AdminCarsType::class, $adminCar);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_cars_index', ['id' => $adminCar->getId()]);
        }

        return $this->render('admin_cars/image_edit.html.twig', [
            'admin_car' => $adminCar,
            'id' => $id,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/iupdate", name="admin_cars_iupdate1", methods="POST")
     */

    public function iupdate(Request $request,$id, AdminCars $adminCar): Response
    {
        $form = $this->createForm(AdminCarsType::class, $adminCar);
        $form->handleRequest($request);
            $file = $request->files->get('imagename');
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
        try {
            $file->move(
                $this->getParameter('images_directory'),
                $fileName
            );
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }
        $adminCar->setImage($fileName);

        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('admin_cars_iedit', ['id' => $adminCar->getId()]);

    }

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }





}

templates/admin_cars/_delete_form.html.twig
<form method="post" action="{{ path('admin_cars_delete', {'id': admin_car.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin_car.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_cars/_form.html.twig
<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="/admin/cars">Araç-İşlemleri</a>
            </li>

        </ol></div>
    <div class="card-body">
        <form method="post">
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">

                            <select name="admin_cars[category_id]" class="form-control-lg" style="width:230px;">

                                {% if (catname) %}
                                <option value="{{ admin_car.categoryid }}" style="font-size:1px;" >{{ catname[0].title }}</option>
                                {% endif %}
                                {% for cat in catlist %}
                                    <option value="{{ cat.id }}">{{ cat.title }}</option>

                                {% endfor %}

                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[title]" value="{{ admin_car.title }}" required="required" maxlength="40">                                <label for="firstName">Title</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[description]" value="{{ admin_car.description }}" required="required" maxlength="40">                                <label for="firstName">Description</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[saleprice]" value="{{ admin_car.saleprice }}" required="required" maxlength="40">                                <label for="firstName">Satış Fiyatı</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[price]" value="{{ admin_car.price }}" required="required" maxlength="40">                                <label for="firstName">Alış Fiyatı</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[keywords]" value="{{ admin_car.keywords }}" required="required" maxlength="40">                            <label for="firstName">Keywords</label>
                        </div>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[status]" value="{{ admin_car.status }}"  maxlength="40">                            <label for="firstName">Status - Online/Offline</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[type]" value="{{ admin_car.type }}" required="required" maxlength="40">                            <label for="firstName">Telefon</label>
                        </div>
                    </div>
                </div>
            </div>
            {% if admin_car.image != null %}
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_cars[image]" value="{{ admin_car.image }}" required="required" maxlength="40">                            <label for="firstName">Image</label>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                         <textarea  id="editor" name="admin_cars[detail]" rows = "10" cols="100" >{{ admin_car.detail }}</textarea>
                        </div>
                    </div>
                </div>
            </div>

            <script>
                ClassicEditor
                    .create( document.querySelector( '#editor' ) )
                    .catch( error => {
                        console.error( error );
                    } );
            </script>



            <button class="btn btn-primary btn-block col-sm-3" type="submit">Kaydet</button>

    </div>

templates/admin_cars/edit.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}Admin-Category{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>

            {{ include('admin_cars/_form.html.twig', {'button_label': 'Update'}) }}


            {% endblock %}

templates/admin_cars/image_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Car Image{% endblock %}

{% block body %}

    <h1>{{ admin_car.title }}</h1>
<form action="{{ path('admin_cars_iupdate1',{'id':id}) }}" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input name="admin_car.id" type = "hidden" value="{{ id }}" type="number" readonly>
    <input type="file" name="imagename" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>
    {% if admin_car.image != null %}
        <img src="/uploads/{{ admin_car.image }}">
    {% endif %}

{% endblock %}

templates/admin_cars/index.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}Product-List index{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb" >
            <li class="breadcrumb-item">
            </li>

            <small><a href="{{ path('admin_cars_new') }}" class="btn btn-block btn-outline-primary">Araç Ekleme</a> </small>


        </ol></div>
    <div class="box-body">
        {% for label, flashes in app.session.flashbag.all %}
            {% for flash in flashes %}
                <div style="width: 1110px;" class="alert alert-{{ label }}">
                    {{ flash }}
                </div>
            {% endfor %}
        {% endfor %}
        <table class="table table-bordered">
            <tbody>
            <tr>


                <th>Title</th>
                <th>Price</th>
                <th>SalePrice</th>
                <th>Detail</th>
                <th>Image</th>
                <th>Galeri</th>


                <th>Status</th>
                <th>Göster</th>
                <th>Sil/Düzenle</th>
            </tr>
        </thead>
            <tbody>
        {% for admin_car in admin_cars %}

            <tr style="line-height: 1px;">

                <td>{{ admin_car.title }}</td>
                <td>{{ admin_car.price }}</td>
                <td>{{ admin_car.saleprice }}</td>
                <td>{{ admin_car.detail|raw }}</td>
                <td>
                    <a href="javascript:openWin('{{ path('admin_cars_iedit', {'id': admin_car.id}) }}','','toolbar=no,location=no,directories=0,status=no,top=100,left=200,menuBar=no,resizable=no,width=1000,heigth=500')">
                    {% if admin_car.image != null %}
                        <img src="/uploads/{{ admin_car.image }}" height="80" width="80">
                    {% else %}
                        Add Image
                        {{ admin_car.image }}


                    {% endif %}
                    </a>

                </td>

                <td>
                    <a href="javascript:openWin('{{ path('admin_image_new', {'pid': admin_car.id}) }}','','toolbar=no,location=no,directories=0,status=no,top=100,left=200,menuBar=no,resizable=no,width=1000,heigth=500')">
                        <img src="/uploads/gallery.png" height="80" width="80"></td></a>
                <td>{{ admin_car.status }}</td>

                <td>
                    <a class="btn btn-primary btn-block col-sm-14" href="{{ path('admin_cars_show', {'id': admin_car.id}) }}">Göster</a>
                </td><td>
                    <a>     {{ include('admin_cars/_delete_form.html.twig') }}</a>
                    <a class="btn btn-primary btn-block col-sm-14" href="{{ path('admin_cars_edit', {'id': admin_car.id}) }}">Düzenle</a>
                </td>




            </tr>
        {% else %}
            <tr>
                <td colspan="17">no records found</td>
            </tr>
            </tbody>
        {% endfor %}




{% endblock %}

templates/admin_cars/new.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}Admin-Category{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>
            {{ include('admin_cars/_form.html.twig') }}

            <a href="{{ path('admin_cars_index') }}">Geri Dön</a>
            {% endblock %}

templates/admin_cars/show.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}Admin-Category{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>



        </ol></div>
    <div class="box-body">
        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ admin_car.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ admin_car.title }}</td>
            </tr>
            <tr>
                <th>Keywords</th>
                <td>{{ admin_car.keywords }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ admin_car.description }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ admin_car.type }}</td>
            </tr>
            <tr>
                <th>Publisher_id</th>
                <td>{{ admin_car.publisherId }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ admin_car.year }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ admin_car.amount }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ admin_car.price }}</td>
            </tr>
            <tr>
                <th>Saleprice</th>
                <td>{{ admin_car.saleprice }}</td>
            </tr>
            <tr>
                <th>Detail</th>
                <td>{{ admin_car.detail }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ admin_car.image }}</td>
            </tr>
            <tr>
                <th>Writer_id</th>
                <td>{{ admin_car.writerId }}</td>
            </tr>
            <tr>
                <th>Category_id</th>
                <td>{{ admin_car.categoryId }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ admin_car.userId }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ admin_car.status }}</td>
            </tr>
        </tbody>
    </table>

    <br>

    <a class="btn btn-primary btn-block col-sm-2" href="{{ path('admin_cars_index') }}">Geri Dön</a>

    </div>
    <!-- /.container-fluid -->



{% endblock %}