src/Entity/AdminCategory.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminCategoryRepository")
 */
class AdminCategory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    public $parent_id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    public $title;

    /**
     * @ORM\Column(type="string", length=40)
     */
    public $keywords;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $description;

    /**
     * @ORM\Column(type="string", length=15)
     */
    public $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }


    public function getKeywords(): ?string
    {
        return $this->keywords;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }


    public function getStatus(): ?string
    {
        return $this->status;
    }


}

src/Form/AdminCategoryType.php
<?php

namespace App\Form;

use App\Entity\AdminCategory;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdminCategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('parent_id')
            ->add('title')
            ->add('keywords')
            ->add('description')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AdminCategory::class,
            'csrf_protection'=>false,
        ]);
    }
}

src/Controller/AdminCategoryController.php
<?php

namespace App\Controller;

use App\Entity\AdminCategory;
use App\Form\AdminCategoryType;
use App\Repository\AdminCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/category")
 */
class AdminCategoryController extends AbstractController
{
    /**
     * @Route("/", name="admin_category_index", methods="GET")
     */
    public function index(AdminCategoryRepository $adminCategoryRepository): Response
    {
        return $this->render('admin_category/index.html.twig', ['admin_categories' => $adminCategoryRepository->findAll()]);
    }

    /**
     * @Route("/new", name="admin_category_new", methods="GET|POST")
     */
    public function new(Request $request,AdminCategoryRepository $categoryrepository): Response
    {
        $CategoryList = $categoryrepository->findBy(['parent_id' => 0]);
        $adminCategory = new AdminCategory();
        $form = $this->createForm(AdminCategoryType::class, $adminCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($adminCategory);
            $em->flush();

            return $this->redirectToRoute('admin_category_index');
        }

        return $this->render('admin_category/new.html.twig', [
            'admin_category' => $adminCategory,
            'CategoryList' => $CategoryList,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_category_show", methods="GET")
     */
    public function show(AdminCategory $adminCategory): Response
    {
        return $this->render('admin_category/show.html.twig', ['admin_category' => $adminCategory]);
    }

    /**
     * @Route("/{id}/{pid}/edit", name="admin_category_edit", methods="GET|POST")
     */
    public function edit(Request $request,$id,$pid, AdminCategoryRepository $categoryrepository, AdminCategory $adminCategory): Response
    {
        $CategoryList = $categoryrepository->findBy(['parent_id' => 0]);
        $CategoryCat = $categoryrepository->findOneBy(['id' => $pid]);
        $form = $this->createForm(AdminCategoryType::class, $adminCategory);
        $form->handleRequest($request);
        #dump($CategoryList);
        #dump($CategoryCat);
        #die();

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash("Success","Güncelleme Basarılı Bir Sekilde Tamamlandı.");
            return $this->redirectToRoute('admin_category_index', ['id' => $adminCategory->getId()]);
        }

        return $this->render('admin_category/edit.html.twig', [
            'admin_category' => $adminCategory,
            'CategoryList' => $CategoryList,
            'CategoryCat' => $CategoryCat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_category_delete", methods="DELETE")
     */
    public function delete(Request $request, AdminCategory $adminCategory): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adminCategory->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($adminCategory);
            $em->flush();
        }

        return $this->redirectToRoute('admin_category_index');
    }
}

templates/admin_category/_delete_form.html.twig
<form method="post" action="{{ path('admin_category_delete', {'id': admin_category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin_category.id) }}">
    <button class="btn btn-primary btn-block col-sm-8">Delete</button>
</form>

templates/admin_category/_form.html.twig
<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="/admin/category">Kategoriler</a>
            </li>

        </ol></div>
    <div class="card-body">
        <form method="post">
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">

                            <select name="admin_category[parent_id]" class="form-control-lg" style="width:230px;">
                                


                                    <option value="0">Ana Kategori</option>
                                    {% for category in CategoryList %}
                                        <option value="{{ category.id }}">{{ category.title }}</option>

                                    {% endfor %}

                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_category[title]" value="{{ admin_category.title }}" required="required" maxlength="40">                                <label for="firstName">Title</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_category[description]" value="{{ admin_category.description }}" required="required" maxlength="40">                                <label for="firstName">Description</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_category[keywords]" value="{{ admin_category.keywords }}" required="required" maxlength="40">                            <label for="firstName">Keywords</label>
                        </div>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-label-group">
                            <input type="text" name="admin_category[status]" value="{{ admin_category.status }}" required="required" maxlength="40">                            <label for="firstName">Status - Online/Offline</label>
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary btn-block col-sm-3" type="submit">Kaydet</button>




    </div>

templates/admin_category/edit.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}Admin-Category{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>

            {{ include('admin_category/_form.html.twig', {'button_label': 'Update'}) }}


{% endblock %}

templates/admin_category/index.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}AdminCategory index{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb" >
            <li class="breadcrumb-item">
            </li>

            <small><a href="{{ path('admin_category_new') }}" class="btn btn-block btn-outline-primary">Kategori Ekleme</a> </small>


        </ol></div>
    <div class="box-body">
        {% for label, flashes in app.session.flashbag.all %}
        {% for flash in flashes %}
            <div style="width: 1110px;" class="alert alert-{{ label }}">
                {{ flash }}
            </div>
        {% endfor %}
        {% endfor %}
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>Id</th>
                <th>Parent_id</th>
                <th>Title</th>
                <th>Keywords</th>
                <th>Description</th>
                <th>Status</th>
                <th>Göster</th>
                <th>Düzenle</th>
                <th>Sil</th>



            </tr>
            {% for admin_category in admin_categories %}
                <tr>
                    <td>{{ admin_category.id }}</td>
                    <td>{{ admin_category.parentId }}</td>
                    <td>{{ admin_category.title }}</td>
                    <td>{{ admin_category.keywords }}</td>
                    <td>{{ admin_category.description }}</td>
                    <td>{{ admin_category.status }}</td>

                    <td>
                        <a class="btn btn-primary btn-block col-sm-9" href="{{ path('admin_category_show', {'id': admin_category.id}) }}">Göster</a>
                    </td><td><a class="btn btn-primary btn-block col-sm-9" href="{{ path('admin_category_edit', {'id': admin_category.id,'pid':admin_category.parent_id}) }}">Düzenle</a>
                    </td>
                    <td> <a>     {{ include('admin_category/_delete_form.html.twig') }}</a></td>

                </tr>
            {% else %}
                <tr>
                    <td colspan="7">no records found</td>
                </tr>
            {% endfor %}
            </tbody>


        </table>

    </div>
    <!-- /.container-fluid -->



{% endblock %}

templates/admin_category/new.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}Admin-Category{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>
    {{ include('admin_category/_form.html.twig') }}

    <a href="{{ path('admin_category_index') }}">Geri Dön</a>
{% endblock %}

templates/admin_category/show.html.twig
{% extends 'admin/admin_header.html.twig' %}


{% block admin_sidebar %}{% include 'admin/admin_sidebar.html.twig' %}{% endblock %}
{% block admin_footer %}{% include 'admin/admin_footer.html.twig' %}{% endblock %}
{% block title %}Admin-Category{% endblock %}

{% block content %}


<div id="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>



        </ol></div>
    <div class="box-body">
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ admin_category.id }}</td>
            </tr>
            <tr>
                <th>Parent_id</th>
                <td>{{ admin_category.parentId }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ admin_category.title }}</td>
            </tr>
            <tr>
                <th>Keywords</th>
                <td>{{ admin_category.keywords }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ admin_category.description }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ admin_category.status }}</td>
            </tr>
        </tbody>
    </table>

        <br>

        <a class="btn btn-primary btn-block col-sm-2" href="{{ path('admin_category_index') }}">Geri Dön</a>

    </div>
    <!-- /.container-fluid -->



    {% endblock %}