src/Entity/AdminDeneme.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminDenemeRepository")
 */
class AdminDeneme
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=230, nullable=true)
     */
    private $deneme;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $id_x;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDeneme(): ?string
    {
        return $this->deneme;
    }

    public function setDeneme(?string $deneme): self
    {
        $this->deneme = $deneme;

        return $this;
    }

    public function getIdX(): ?int
    {
        return $this->id_x;
    }

    public function setIdX(?int $id_x): self
    {
        $this->id_x = $id_x;

        return $this;
    }
}

src/Form/AdminDenemeType.php
<?php

namespace App\Form;

use App\Entity\AdminDeneme;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdminDenemeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('deneme')
            ->add('id_x')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AdminDeneme::class,
        ]);
    }
}

src/Controller/AdminDenemeController.php
<?php

namespace App\Controller;

use App\Entity\AdminDeneme;
use App\Form\AdminDenemeType;
use App\Repository\AdminDenemeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/deneme")
 */
class AdminDenemeController extends AbstractController
{
    /**
     * @Route("/", name="admin_deneme_index", methods="GET")
     */
    public function index(AdminDenemeRepository $adminDenemeRepository): Response
    {
        return $this->render('admin_deneme/index.html.twig', ['admin_denemes' => $adminDenemeRepository->findAll()]);
    }

    /**
     * @Route("/new", name="admin_deneme_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $adminDeneme = new AdminDeneme();
        $form = $this->createForm(AdminDenemeType::class, $adminDeneme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($adminDeneme);
            $em->flush();

            return $this->redirectToRoute('admin_deneme_index');
        }

        return $this->render('admin_deneme/new.html.twig', [
            'admin_deneme' => $adminDeneme,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_deneme_show", methods="GET")
     */
    public function show(AdminDeneme $adminDeneme): Response
    {
        return $this->render('admin_deneme/show.html.twig', ['admin_deneme' => $adminDeneme]);
    }

    /**
     * @Route("/{id}/edit", name="admin_deneme_edit", methods="GET|POST")
     */
    public function edit(Request $request, AdminDeneme $adminDeneme): Response
    {
        $form = $this->createForm(AdminDenemeType::class, $adminDeneme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_deneme_index', ['id' => $adminDeneme->getId()]);
        }

        return $this->render('admin_deneme/edit.html.twig', [
            'admin_deneme' => $adminDeneme,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_deneme_delete", methods="DELETE")
     */
    public function delete(Request $request, AdminDeneme $adminDeneme): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adminDeneme->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($adminDeneme);
            $em->flush();
        }

        return $this->redirectToRoute('admin_deneme_index');
    }
}

templates/admin_deneme/_delete_form.html.twig
<form method="post" action="{{ path('admin_deneme_delete', {'id': admin_deneme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin_deneme.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_deneme/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_deneme/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AdminDeneme{% endblock %}

{% block body %}
    <h1>Edit AdminDeneme</h1>

    {{ include('admin_deneme/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('admin_deneme_index') }}">back to list</a>

    {{ include('admin_deneme/_delete_form.html.twig') }}
{% endblock %}

templates/admin_deneme/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AdminDeneme index{% endblock %}

{% block body %}
    <h1>AdminDeneme index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Deneme</th>
                <th>Id_x</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for admin_deneme in admin_denemes %}
            <tr>
                <td>{{ admin_deneme.id }}</td>
                <td>{{ admin_deneme.deneme }}</td>
                <td>{{ admin_deneme.idX }}</td>
                <td>
                    <a href="{{ path('admin_deneme_show', {'id': admin_deneme.id}) }}">show</a>
                    <a href="{{ path('admin_deneme_edit', {'id': admin_deneme.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('admin_deneme_new') }}">Create new</a>
{% endblock %}

templates/admin_deneme/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AdminDeneme{% endblock %}

{% block body %}
    <h1>Create new AdminDeneme</h1>

    {{ include('admin_deneme/_form.html.twig') }}

    <a href="{{ path('admin_deneme_index') }}">back to list</a>
{% endblock %}

templates/admin_deneme/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AdminDeneme{% endblock %}

{% block body %}
    <h1>AdminDeneme</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ admin_deneme.id }}</td>
            </tr>
            <tr>
                <th>Deneme</th>
                <td>{{ admin_deneme.deneme }}</td>
            </tr>
            <tr>
                <th>Id_x</th>
                <td>{{ admin_deneme.idX }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_deneme_index') }}">back to list</a>

    <a href="{{ path('admin_deneme_edit', {'id': admin_deneme.id}) }}">edit</a>

    {{ include('admin_deneme/_delete_form.html.twig') }}
{% endblock %}